# Generated by Django 3.2.13 on 2022-04-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostEmail', models.EmailField(max_length=254)),
                ('participantEmail', models.EmailField(max_length=254)),
                ('chathistory', models.CharField(max_length=100)),
                ('chatRoom', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('initiatedDateTime', models.DateTimeField()),
                ('completedDateTime', models.DateTimeField()),
            ],
        ),
    ]
